name: autoproof
version: 0.0.0.0
license: BSD3
author: "Artem Mavrin"
maintainer: "artemvmavrin@gmail.com"
copyright: "2021 Artem Mavrin"
github: "artemmavrin/autoproof"
category: Logic
synopsis: Propositional logic library

extra-source-files:
  - README.md

description: |

  The intended entry points into this library are

  1.  "AutoProof.Classical", for classical logic, and
  2.  "AutoProof.Intuitionistic", for intuitionistic logic.

  Please see the README on GitHub at <https://github.com/artemmavrin/autoproof#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.4.1

library:
  source-dirs: src
  ghc-options:
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

executables:
  autoproof:
    main: Main.hs
    source-dirs: app/autoproof
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - autoproof
    when:
      - condition: false
        other-modules: Paths_autoproof

tests:
  formula-test:
    main: Main.hs
    source-dirs: test/internal/formula
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -O0
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  judgement-test:
    main: Main.hs
    source-dirs: test/internal/judgement
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -O0
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  proof-test:
    main: Main.hs
    source-dirs: test/internal/proof
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -O0
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  parser-test:
    main: Main.hs
    source-dirs: test/internal/parser
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  dlist-test:
    main: Main.hs
    source-dirs: test/internal/dlist
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  prove-imp-test:
    main: Main.hs
    source-dirs: test/intuitionistic/prove-imp
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  is-tautology-test:
    main: Main.hs
    source-dirs: test/intuitionistic/is-tautology
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  prove-tautology-test:
    main: Main.hs
    source-dirs: test/intuitionistic/prove-tautology
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  prove-statman-test:
    main: Main.hs
    source-dirs: test/intuitionistic/prove-statman
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  prove-test:
    main: Main.hs
    source-dirs: test/intuitionistic/prove
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  glivenko-test:
    main: Main.hs
    source-dirs: test/classical/glivenko
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  provable-test:
    main: Main.hs
    source-dirs: test/classical/provable
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
  cnf-test:
    main: Main.hs
    source-dirs: test/classical/cnf
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    dependencies:
      - autoproof
      - hspec >= 0.8.2
      - QuickCheck >= 2.14.2
    when:
      - condition: false
        other-modules: Paths_autoproof
