name:                proof
version:             0.0.0.0
license:             BSD3
author:              "Artem Mavrin"
maintainer:          "artemvmavrin@gmail.com"
copyright:           "2021 Artem Mavrin"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  imp-test:
    main:                ImpSpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - proof
    - hspec >= 0.8.2
    when:
    - condition: false
      other-modules: Paths_proof
