name:                proof
version:             0.0.0.0
license:             BSD3
author:              "Artem Mavrin"
maintainer:          "artemvmavrin@gmail.com"
copyright:           "2021 Artem Mavrin"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
