name:                proof
version:             0.0.0.0
license:             BSD3
author:              "Artem Mavrin"
maintainer:          "artemvmavrin@gmail.com"
copyright:           "2021 Artem Mavrin"
category:            Logic
synopsis:            Intuitionistic natural deduction prover

extra-source-files:
- README.md
description:         Please see the README on GitHub at <https://github.com/artemmavrin/proof#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.4.1
- parsec >= 3.1.14.0

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

tests:
  imp-test:
    main:                Spec.hs
    source-dirs:         test/imp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - proof
    - hspec >= 0.8.2
    when:
    - condition: false
      other-modules: Paths_proof
