name:                autoproof
version:             0.0.0.0
license:             BSD3
author:              "Artem Mavrin"
maintainer:          "artemvmavrin@gmail.com"
copyright:           "2021 Artem Mavrin"
github:              "artemmavrin/autoproof"
category:            Logic
synopsis:            Propositional intuitionistic natural deduction

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/artemmavrin/autoproof#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.4.1
- parsec >= 3.1.14.0

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

tests:
  formula-test:
    main:                Main.hs
    source-dirs:         test/spec/formula
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O0
    dependencies:
    - autoproof
    - hspec >= 0.8.2
    - QuickCheck >= 2.14.2
    when:
    - condition: false
      other-modules: Paths_autoproof
  proof-test:
    main:                Main.hs
    source-dirs:         test/spec/proof
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O0
    dependencies:
    - autoproof
    - hspec >= 0.8.2
    - QuickCheck >= 2.14.2
    when:
    - condition: false
      other-modules: Paths_autoproof
  parser-test:
    main:                Main.hs
    source-dirs:         test/spec/parser
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - autoproof
    - hspec >= 0.8.2
    - QuickCheck >= 2.14.2
    when:
    - condition: false
      other-modules: Paths_autoproof
  prove-imp-test:
    main:                Main.hs
    source-dirs:         test/spec/prove-imp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - autoproof
    - hspec >= 0.8.2
    - QuickCheck >= 2.14.2
    when:
    - condition: false
      other-modules: Paths_autoproof
  strengthen-proof-imp-test:
    main:                Main.hs
    source-dirs:         test/spec/strengthen-proof-imp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - autoproof
    - hspec >= 0.8.2
    - QuickCheck >= 2.14.2
    when:
    - condition: false
      other-modules: Paths_autoproof
  is-tautology-test:
    main:                Main.hs
    source-dirs:         test/spec/is-tautology
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - autoproof
    - hspec >= 0.8.2
    - QuickCheck >= 2.14.2
    when:
    - condition: false
      other-modules: Paths_autoproof

executables:
  parseFormula:
    main:                Main.hs
    source-dirs:         test/repl/parseFormula
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - autoproof
    when:
    - condition: false
      other-modules: Paths_autoproof
  parseJudgement:
    main:                Main.hs
    source-dirs:         test/repl/parseJudgement
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - autoproof
    when:
    - condition: false
      other-modules: Paths_autoproof
  proveImp:
    main:                Main.hs
    source-dirs:         test/repl/proveImp
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - autoproof
    when:
    - condition: false
      other-modules: Paths_autoproof
  statman:
    main:                Main.hs
    source-dirs:         test/repl/statman
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - autoproof
    when:
    - condition: false
      other-modules: Paths_autoproof
