on:
  push:
    branches:
      - main
name: docs
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: latest
          cabal-version: latest
          enable-stack: true
          stack-version: latest

      - name: Build docs
        run: |
          stack haddock --fast --no-haddock-deps
          mkdir -p docs && mv $(stack path --local-install-root)/doc/* docs
          echo "<meta http-equiv=\"refresh\" content=\"0; url=./autoproof-$(stack ls dependencies | grep autoproof | awk '{print $2}')/\" />" >> docs/index.html

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs
