on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['latest']
        cabal: ['latest']
        stack: ['latest']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: OS ${{ matrix.os }}, GHC ${{ matrix.ghc }}, Cabal ${{ matrix.cabal }}, Stack ${{ matrix.stack }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: true
          stack-version: ${{ matrix.stack }}
      - run: stack test
