on: [push]
name: test
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["latest"]
        cabal: ["latest"]
        stack: ["latest"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: OS ${{ matrix.os }}, GHC ${{ matrix.ghc }}, Cabal ${{ matrix.cabal }}, Stack ${{ matrix.stack }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: true
          stack-version: ${{ matrix.stack }}
      - run: stack test --coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: stack test
        if: ${{ matrix.os != 'ubuntu-latest' }}
      - name: Generate coverage report
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: 8c6794b6/hpc-codecov-action@v2
        with:
          target: stack:all
          excludes: Paths_autoproof
      - name: Send coverage report
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v3.1.2
